name: Build and Deploy Firmware

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up PlatformIO
      - name: Set up PlatformIO
        uses: platformio/platformio-action@v2

      # 3. Build firmware for SAMD21J18
      - name: Build firmware
        run: |
          platformio run -e uno
          mkdir -p build
          # Copy the generated binary to 'build' folder
          cp ./.pio/build/samd21j18/firmware.hex ./build/binary.hex

      # 4. Upload firmware via FTP to AwardSpace
      - name: Upload firmware via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.awardspace.net
          username: 4669949_Yassine # Replace with your FTP username
          password: D7uWgUPQ*a # Replace with your FTP password
          local-dir: ./build
          server-dir: /yassine.mywebcommunity.org/